### ISSUE TITLE
Converting into VB.NET Class

### ISSUE THREAD

**Issue by Moatassem** [mzboray/HighPrecisionTimer#1]
[HPT.zip](https://github.com/mzboray/HighPrecisionTimer/files/1555824/HPT.zip)
Hello Mike,

Great work with this timer.

I have been looking for a decent precise multimedia timer wrapper around winmm.dll. Yours is fantastic indeed. Outstanding work!

I am working on a media streamer using VB.NET and need to integrate your timer natively within my code. 
May I?

If yes, can you please guide me to properly correct my conversion of your C# class into VB?

Thanks a lot.

**Comment by mzboray** [comment]
Sure, you can use it.

I don't really have time to provide a lot of guidance or any particular expertise in VB.NET, but this tool seems to do a decent job: http://converter.telerik.com/

The one thing you will need to change is the use of `volatile`. VB.NET has no direct equivalent, but from what I can see the only use is on the `timerId` field. You could create something equivalent using `lock` (or SyncLock in VB.NET). All you need to do is wrap reading and writing the field in a lock statement. After making that small change, the converter worked but I did not test the converted code.

Hope that helps. Good luck.

**Comment by Moatassem** [comment]
Thanks a lot Mike.

I got it working just after posting my reply.

It was a problem in the timerId field indeed.



Best Regards,
*Moatassem Talaat*
Voice Core Network Expert
Elite Telecom Software Developer
Cell: +20 1223309859
LinkedIn Profile <https://www.linkedin.com/in/moatassem-talaat-53699714/> -
SkypeID: Moatassem Talaat
