### ISSUE TITLE
[Question] Any limit on how many multimedia timers an application can have at once?

### ISSUE THREAD

**Issue by layer07** [mzboray/HighPrecisionTimer#2]
Been reading a lot about Multimedia timers, one thing I cannot understand yet is: Why a lot of documentation mentions that we have a "set limit" for the number of multimedia timers we can have? 

I've been basically running a lot of them at the same time, and I don't see any performance degradation. Yet I've read on Stackoverflow/MSDN people mentioning that the "maximum multimedia timers we can have per application is 16, yet 12 will cause the PC to lag".

Are this people using potatoes as computer or your implementation bypasses this limit? Is it a true multimedia timer? What is going on?

Thanks

**Comment by mzboray** [comment]
I'm not really an expert with this API but I did some testing based on your question and on Windows 10 at least there does appear to be a limit of 16 multimedia timers. An error is returned from timerSetEvent afterwards. The timerSetEvent function is only called from Start so is it possible you have many MultimediaTimer objects and less than 16 are started/running? This is the only way I can think of this code avoiding hitting the limit.

**Comment by layer07** [comment]
Didn't see your answer, sorry about that.

It seems that it gets unstable after you launch too many of them. That is weird lol. I would like to test it more thoroughly. But I am still somewhat frustrated to see that we can't really time actions precisely on .NET

Let's say we want to iterate 1000times or 2500 times a second on a function _because we WANT to_, or because **we NEED to**. Nope, forget about that.

Don't take my word as final, but I will test to see if I can have like, 1000 instances of this running without receiving a weird error. 

This is what I tend to get after starting a lot of timer instances "System.ComponentModel.Win32Exception: 'The operation completed successfully'"
